# # # # # # # # # # # # # # # # # # # # # # #
#                                           #
#           Plugin developed by             #
#                fcPlugins                  #
#     https://t.me/fcplugins_minecraft      #
#                                           #
# # # # # # # # # # # # # # # # # # # # # # #

chat:
  enabled: true
  prefix: "!"

local-chat:
  radius: 100
  format: "&bⓁ %prefix%&f{player}%suffix%&b: &f{message}"

global-chat:
  format: "&6Ⓖ %prefix%&f{player}%suffix%&6: &f{message}"

copy:
  enabled: true
  permission: "fcchat.copy"
  hover-text: "&7[&fCopy message&7]"

color-chat:
  enabled: true
  permission: "fcchat.color"

hidden-text:
  enabled: true
  permission: "fcchat.hidden"
  symbol: "█"
  length: 7

player-info:
  enabled: true
  permission: "fcchat.info"
  lines:
    - "&7[⚠] &fPlayer Information&7: %player_name%"
    - "&f"
    - "&7» &fLast joined&7: %player_last_played_formatted%"
    - "&7» &fCountry&7: %player_locale_country%"
    - "&7» &fIP Address&7: %player_ip%"
    - "&7» &fPing&7: %player_ping%"

discord:
  enabled: false
  webhook-url: ""
  message-format: "{player}: {message}"

spy:
  enabled: true
  permission: "fcchat.spy"
  message-format: "&9Ⓢ &7{formatted}"

join-leave-messages:
  enabled: true
  join:
    message: "&a&l+&f %player_name%"
    sound: "ENTITY_PLAYER_LEVELUP"
  leave:
    message: "&c&l-&f %player_name%"
    sound: "ENTITY_PLAYER_LEVELUP"

disabled-worlds:
  - "disableWorld1"
  - "disableWorld2"

hologram-messages:
  enabled: false
  duration: 10
  max-words-per-line: 6
  height: 2.5
  format: "&f{message}"

sounds:
  message:
    enabled: true
    sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 0.5
    pitch: 1.0
  ping:
    enabled: true
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 0.8
    pitch: 1.2
  everyone-ping:
    enabled: true
    sound: "ENTITY_ENDER_DRAGON_GROWL"
    volume: 1.0
    pitch: 0.8

ping-system:
  enabled: true
  permission: "fcchat.ping"
  everyone-permission: "fcchat.ping.everyone"
  ping-color: "&e"
  everyone-ping-color: "&c"

update-check: true